settings:
    log_level: INFO
    update_interval: 250
    market_pairs:
        - 1000SHIB/USDT

exchanges:
    binance:
        required:
            enabled: true

indicators:
    # rsi:
    #     - enabled: true
    #       alert_enabled: false
    #       alert_frequency: once
    #       signal:
    #         - rsi
    #       hot: 30
    #       cold: 70
    #       candle_period: 1h
    #       period_count: 50
    #     - enabled: true
    #       alert_enabled: true
    #       alert_frequency: once
    #       signal:
    #         - rsi
    #       hot: 30
    #       cold: 70
    #       candle_period: 5m
    #       period_count: 14
    # stoch_rsi:
    #     - enabled: true
    #       alert_enabled: true
    #       alert_frequency: once
    #       signal:
    #         - stoch_rsi
    #       hot: 20
    #       cold: 80
    #       candle_period: 5m
    #       period_count: 14
    # momentum:
    #     - enabled: true
    #       alert_enabled: false
    #       alert_frequency: once
    #       signal:
    #         - momentum
    #       hot: 0
    #       cold: 0
    #       candle_period: 1d
    #       period_count: 10
    #     - enabled: true
    #       alert_enabled: false
    #       alert_frequency: once
    #       signal:
    #         - momentum
    #       hot: 0
    #       cold: 0
    #       candle_period: 1h
    #       period_count: 12
    macd:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - macd
          hot: 0
          cold: 0
          candle_period: 5m
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - macdsignal
          hot: 0
          cold: 0
          candle_period: 5m
    # obv:
    #     - enabled: false
    # mfi:
    #     - enabled: true
    #       alert_enabled: true
    #       alert_frequency: once
    #       signal:
    #         - mfi
    #       hot: 20
    #       cold: 80
    #       candle_period: 5m
    #       period_count: 14
    # ichimoku:
    #     - enabled: false

# informants:
    # ema:
        # - enabled: true
        #   signal:
        #     - ema
        #   candle_period: 1d
        #   period_count: 10
        # - enabled: true
        #   signal:
        #     - ema
        #   candle_period: 1d
        #   period_count: 30

crossovers:
    std_crossover:
        # - enabled: true
        #   alert_enabled: true
        #   alert_frequency: once
        #   key_indicator: ema
        #   key_indicator_index: 0
        #   key_indicator_type: informants
        #   key_signal: ema
        #   crossed_indicator: ema
        #   crossed_indicator_index: 1
        #   crossed_indicator_type: informants
        #   crossed_signal: ema
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: macd
          key_indicator_index: 0
          key_indicator_type: indicators
          key_signal: macd
          crossed_indicator: macd
          crossed_indicator_index: 1
          crossed_indicator_type: indicators
          crossed_signal: macdsignal

notifiers:
  telegram:
      required:
        token: 1702985121:AAEJ1ycqLbtLrQ5o43LT9iwlUPOcsnDZoh4
        chat_id: 1713290524
      optional:
          parse_mode: html
          template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}"

  webhook:
    required:
      url: https://webhook.site/28a77dbd-b0b7-493b-9bb3-aad019d0c963
      # url: http://10.5.50.69:3000/webhook
    optional:
      username: null
      password: null
